export type GalleryPhoto = {
  src: string;
  alt: string;
  caption: string;
  note: string;
  originalName: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait";
};

// This file is generated by scripts/sync-family-gallery.ps1.
// Re-run the script after adding, removing, or renaming source images in /images.
export const heroPhoto = {
    "src":  "/family-gallery/family-fall-28.jpg",
    "alt":  "Mieszko Gorski with his wife in an autumn portrait",
    "caption":  "Autumn portrait",
    "note":  "A calm, elegant portrait that feels especially warm and timeless.",
    "originalName":  "FAMILY FALL-28.jpg",
    "width":  3648,
    "height":  5472,
    "orientation":  "portrait"
} as const satisfies GalleryPhoto;

export const featuredPhotos = [
    {
        "src":  "/family-gallery/family-fall-28.jpg",
        "alt":  "Mieszko Gorski with his wife in an autumn portrait",
        "caption":  "Autumn portrait",
        "note":  "A calm, elegant portrait that feels especially warm and timeless.",
        "originalName":  "FAMILY FALL-28.jpg",
        "width":  3648,
        "height":  5472,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/drl6135.jpg",
        "alt":  "Mieszko Gorski in a blue suit with his wife at a formal family event",
        "caption":  "Formal celebration",
        "note":  "An elegant portrait from a family celebration.",
        "originalName":  "_DRL6135.jpg",
        "width":  4024,
        "height":  6048,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/fall-family-90.jpg",
        "alt":  "Mieszko Gorski with family by a lake in the fall",
        "caption":  "By the lake",
        "note":  "A gentle family moment outdoors in autumn.",
        "originalName":  "Fall Family-90.jpg",
        "width":  5472,
        "height":  3648,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/family-fall-21.jpg",
        "alt":  "Mieszko Gorski with his family in an autumn portrait",
        "caption":  "Family legacy",
        "note":  "A multi-generational family portrait full of warmth and continuity.",
        "originalName":  "FAMILY FALL-21.jpg",
        "width":  5472,
        "height":  3648,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2025-christmas-19.jpg",
        "alt":  "Mieszko Gorski with family in a Christmas portrait",
        "caption":  "Christmas gathering",
        "note":  "A bright holiday portrait centered on family togetherness.",
        "originalName":  "2025 Christmas-19.jpg",
        "width":  5344,
        "height":  3503,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/drl5039.jpg",
        "alt":  "Mieszko Gorski standing with his son at a formal occasion",
        "caption":  "Father and son",
        "note":  "A composed portrait that emphasizes family connection.",
        "originalName":  "_DRL5039.jpg",
        "width":  4000,
        "height":  5460,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/g0064512.jpg",
        "alt":  "Mieszko Gorski smiling before a skydiving experience",
        "caption":  "Adventure",
        "note":  "A joyful image that shows curiosity, courage, and playfulness.",
        "originalName":  "G0064512.JPG",
        "width":  3648,
        "height":  2736,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/1111171942c.jpg",
        "alt":  "Mieszko Gorski standing near a waterfront during travel",
        "caption":  "Travel portrait",
        "note":  "A reflective solo image from a trip abroad.",
        "originalName":  "1111171942c.jpg",
        "width":  3264,
        "height":  1836,
        "orientation":  "landscape"
    }
] as const satisfies readonly GalleryPhoto[];

export const archivePhotos = [
    {
        "src":  "/family-gallery/family-fall-28.jpg",
        "alt":  "Mieszko Gorski with his wife in an autumn portrait",
        "caption":  "Autumn portrait",
        "note":  "A calm, elegant portrait that feels especially warm and timeless.",
        "originalName":  "FAMILY FALL-28.jpg",
        "width":  3648,
        "height":  5472,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/drl6135.jpg",
        "alt":  "Mieszko Gorski in a blue suit with his wife at a formal family event",
        "caption":  "Formal celebration",
        "note":  "An elegant portrait from a family celebration.",
        "originalName":  "_DRL6135.jpg",
        "width":  4024,
        "height":  6048,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/fall-family-90.jpg",
        "alt":  "Mieszko Gorski with family by a lake in the fall",
        "caption":  "By the lake",
        "note":  "A gentle family moment outdoors in autumn.",
        "originalName":  "Fall Family-90.jpg",
        "width":  5472,
        "height":  3648,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/family-fall-21.jpg",
        "alt":  "Mieszko Gorski with his family in an autumn portrait",
        "caption":  "Family legacy",
        "note":  "A multi-generational family portrait full of warmth and continuity.",
        "originalName":  "FAMILY FALL-21.jpg",
        "width":  5472,
        "height":  3648,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2025-christmas-19.jpg",
        "alt":  "Mieszko Gorski with family in a Christmas portrait",
        "caption":  "Christmas gathering",
        "note":  "A bright holiday portrait centered on family togetherness.",
        "originalName":  "2025 Christmas-19.jpg",
        "width":  5344,
        "height":  3503,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/drl5039.jpg",
        "alt":  "Mieszko Gorski standing with his son at a formal occasion",
        "caption":  "Father and son",
        "note":  "A composed portrait that emphasizes family connection.",
        "originalName":  "_DRL5039.jpg",
        "width":  4000,
        "height":  5460,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/g0064512.jpg",
        "alt":  "Mieszko Gorski smiling before a skydiving experience",
        "caption":  "Adventure",
        "note":  "A joyful image that shows curiosity, courage, and playfulness.",
        "originalName":  "G0064512.JPG",
        "width":  3648,
        "height":  2736,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/1111171942c.jpg",
        "alt":  "Mieszko Gorski standing near a waterfront during travel",
        "caption":  "Travel portrait",
        "note":  "A reflective solo image from a trip abroad.",
        "originalName":  "1111171942c.jpg",
        "width":  3264,
        "height":  1836,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/drl6161.jpg",
        "alt":  "Photo of Mieszko Gorski from the family archive",
        "caption":  "Family archive",
        "note":  "A photograph from the family archive.",
        "originalName":  "_DRL6161.jpg",
        "width":  4024,
        "height":  6048,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/040311-05.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "040311 05.JPG",
        "width":  1024,
        "height":  768,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/0406tn-350.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "0406TN 350.jpg",
        "width":  768,
        "height":  1024,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/0406tn-416.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "0406TN 416.jpg",
        "width":  1024,
        "height":  768,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/1014161748d.jpg",
        "alt":  "Photo of Mieszko Gorski from the family archive",
        "caption":  "Family archive",
        "note":  "A photograph from the family archive.",
        "originalName":  "1014161748d.jpg",
        "width":  3264,
        "height":  1836,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/101sam-1789.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "101SAM_1789.JPG",
        "width":  1920,
        "height":  1080,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2005050702.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "2005050702.JPG",
        "width":  1024,
        "height":  768,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2009-09-pl-306.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "2009-09-PL 306.jpg",
        "width":  1280,
        "height":  960,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2009-09-pl-415.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "2009-09-PL 415.jpg",
        "width":  1280,
        "height":  960,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/20100307-002.jpg",
        "alt":  "Photo of Mieszko Gorski from the family archive",
        "caption":  "Family archive",
        "note":  "A photograph from the family archive.",
        "originalName":  "20100307 002.JPG",
        "width":  2048,
        "height":  1536,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2010-03-fl-154.jpg",
        "alt":  "Mieszko Gorski during a family trip",
        "caption":  "Travel years",
        "note":  "A travel photograph from the family archive.",
        "originalName":  "2010-03-FL 154.JPG",
        "width":  2048,
        "height":  1536,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2010-04-bahamascruise-169.jpg",
        "alt":  "Mieszko Gorski during a family trip",
        "caption":  "Travel years",
        "note":  "A travel photograph from the family archive.",
        "originalName":  "2010-04-BahamasCruise 169.JPG",
        "width":  2048,
        "height":  1536,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2010-04-bahamascruise-193.jpg",
        "alt":  "Mieszko Gorski during a family trip",
        "caption":  "Travel years",
        "note":  "A travel photograph from the family archive.",
        "originalName":  "2010-04-BahamasCruise 193.JPG",
        "width":  2048,
        "height":  1536,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2010-04-bahamascruise-233.jpg",
        "alt":  "Mieszko Gorski during a family trip",
        "caption":  "Travel years",
        "note":  "A travel photograph from the family archive.",
        "originalName":  "2010-04-BahamasCruise 233.JPG",
        "width":  2048,
        "height":  1536,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2010-06-12-13-071.jpg",
        "alt":  "Mieszko Gorski during a family trip",
        "caption":  "Travel years",
        "note":  "A travel photograph from the family archive.",
        "originalName":  "2010-06-12-13 071.JPG",
        "width":  2048,
        "height":  1536,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2025-christmas-12.jpg",
        "alt":  "Mieszko Gorski in a Christmas family photo",
        "caption":  "Christmas with family",
        "note":  "A holiday moment from the family archive.",
        "originalName":  "2025 Christmas-12.jpg",
        "width":  5149,
        "height":  3352,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/2025-christmas-21.jpg",
        "alt":  "Mieszko Gorski in a Christmas family photo",
        "caption":  "Christmas with family",
        "note":  "A holiday moment from the family archive.",
        "originalName":  "2025 Christmas-21.jpg",
        "width":  3598,
        "height":  5397,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/fall-family-31.jpg",
        "alt":  "Mieszko Gorski in an autumn family portrait",
        "caption":  "Autumn family portrait",
        "note":  "An outdoor family portrait from the autumn collection.",
        "originalName":  "Fall Family-31.jpg",
        "width":  3648,
        "height":  5472,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/fall-family-33.jpg",
        "alt":  "Mieszko Gorski in an autumn family portrait",
        "caption":  "Autumn family portrait",
        "note":  "An outdoor family portrait from the autumn collection.",
        "originalName":  "Fall Family-33.jpg",
        "width":  3648,
        "height":  5472,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/family-fall-27.jpg",
        "alt":  "Mieszko Gorski in an autumn family portrait",
        "caption":  "Autumn family portrait",
        "note":  "An outdoor family portrait from the autumn collection.",
        "originalName":  "FAMILY FALL-27.jpg",
        "width":  3648,
        "height":  5472,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/g0074523.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "G0074523.JPG",
        "width":  3648,
        "height":  2736,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-0212.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_0212.JPG",
        "width":  1920,
        "height":  1080,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-0688.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_0688.JPG",
        "width":  5712,
        "height":  4284,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-0691.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_0691.JPG",
        "width":  5712,
        "height":  4284,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-0692.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_0692.JPG",
        "width":  5712,
        "height":  4284,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-0694.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_0694.JPG",
        "width":  5712,
        "height":  4284,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-0819.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_0819.JPG",
        "width":  5712,
        "height":  4284,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-0961.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_0961.JPG",
        "width":  4032,
        "height":  3024,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-0982.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_0982.JPG",
        "width":  3088,
        "height":  2320,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-1314.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_1314.JPG",
        "width":  2048,
        "height":  1536,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-2367.jpg",
        "alt":  "Photo of Mieszko Gorski from the family archive",
        "caption":  "Family archive",
        "note":  "A photograph from the family archive.",
        "originalName":  "IMG_2367.jpg",
        "width":  4032,
        "height":  3024,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/img-9715.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "IMG_9715.JPG",
        "width":  4032,
        "height":  3024,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/picture-002.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "Picture 002.jpg",
        "width":  1024,
        "height":  768,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/picture-375.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "Picture 375.jpg",
        "width":  1280,
        "height":  960,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/picture-428.jpg",
        "alt":  "Earlier photo of Mieszko Gorski",
        "caption":  "Earlier chapter",
        "note":  "An earlier photograph preserved in the archive.",
        "originalName":  "Picture 428.jpg",
        "width":  1280,
        "height":  960,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/sam-0313.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "SAM_0313.JPG",
        "width":  1920,
        "height":  1080,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/sam-0578.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "SAM_0578.JPG",
        "width":  1920,
        "height":  1080,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/sam-1409.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "SAM_1409.JPG",
        "width":  1920,
        "height":  1080,
        "orientation":  "landscape"
    },
    {
        "src":  "/family-gallery/sam-2432.jpg",
        "alt":  "Mieszko Gorski in a family archive photo",
        "caption":  "Family archive",
        "note":  "A candid moment from family life.",
        "originalName":  "SAM_2432.JPG",
        "width":  1080,
        "height":  1920,
        "orientation":  "portrait"
    },
    {
        "src":  "/family-gallery/td-018.jpg",
        "alt":  "Photo of Mieszko Gorski from the family archive",
        "caption":  "Family archive",
        "note":  "A photograph from the family archive.",
        "originalName":  "TD-018.jpg",
        "width":  4000,
        "height":  6000,
        "orientation":  "portrait"
    }
] as const satisfies readonly GalleryPhoto[];

export const gallerySummary = {
  totalPhotos: 48,
  featuredPhotos: 8,
  unsupportedFiles: [
    "0520171831.mp4",
    "GOPR4463.MP4",
    "GOPR4465.MP4",
    "IMG_4478.MOV",
    "IMG_5208.HEIC",
    "IMG_8491.MOV"
],
} as const;
