export type MusicTrack = {
  src: string;
  fileName: string;
  title: string;
  duration: string;
  description: string;
  inspiration: string;
  featured: boolean;
  background: boolean;
};

// This file is generated by scripts/sync-music-library.ps1.
// Re-run the script after updating the source recordings in /Music.
export const backgroundTrack = {
    "src":  "/music-library/whisperingspaces.mp3",
    "fileName":  "WhisperingSpaces.mp3",
    "title":  "Whispering Spaces",
    "duration":  "00:02:38",
    "description":  "A quiet, meditative piece that works beautifully as an ambient thread through the tribute site.",
    "inspiration":  "Chosen as the site\u0027s background track for its gentle, reflective atmosphere.",
    "featured":  false,
    "background":  true
} as const satisfies MusicTrack;

export const featuredTrack = {
    "src":  "/music-library/semperanticus.mp3",
    "fileName":  "SemperAnticus.mp3",
    "title":  "Semper Anticus",
    "duration":  "00:06:30",
    "description":  "A substantial and dignified work that gives the music page a strong dramatic center.",
    "inspiration":  "A featured track that suggests endurance, gravity, and continuity.",
    "featured":  true,
    "background":  false
} as const satisfies MusicTrack;

export const musicLibrary = [
    {
        "src":  "/music-library/whisperingspaces.mp3",
        "fileName":  "WhisperingSpaces.mp3",
        "title":  "Whispering Spaces",
        "duration":  "00:02:38",
        "description":  "A quiet, meditative piece that works beautifully as an ambient thread through the tribute site.",
        "inspiration":  "Chosen as the site\u0027s background track for its gentle, reflective atmosphere.",
        "featured":  false,
        "background":  true
    },
    {
        "src":  "/music-library/semperanticus.mp3",
        "fileName":  "SemperAnticus.mp3",
        "title":  "Semper Anticus",
        "duration":  "00:06:30",
        "description":  "A substantial and dignified work that gives the music page a strong dramatic center.",
        "inspiration":  "A featured track that suggests endurance, gravity, and continuity.",
        "featured":  true,
        "background":  false
    },
    {
        "src":  "/music-library/dreamstocome.mp3",
        "fileName":  "DreamsToCome.mp3",
        "title":  "Dreams to Come",
        "duration":  "00:04:43",
        "description":  "A forward-looking composition filled with promise and open space.",
        "inspiration":  "A reflection on possibility, future seasons, and imagination still unfolding.",
        "featured":  true,
        "background":  false
    },
    {
        "src":  "/music-library/watchingstars.mp3",
        "fileName":  "WatchingStars.mp3",
        "title":  "Watching Stars",
        "duration":  "00:04:19",
        "description":  "A contemplative piece that feels expansive, patient, and quietly luminous.",
        "inspiration":  "Inspired by wonder, distance, and the calm of looking upward.",
        "featured":  true,
        "background":  false
    },
    {
        "src":  "/music-library/sailingaway.mp3",
        "fileName":  "SailingAway.mp3",
        "title":  "Sailing Away",
        "duration":  "00:03:10",
        "description":  "Music shaped by movement, distance, and the emotional texture of departure.",
        "inspiration":  "A voyage piece about transition, memory, and horizon.",
        "featured":  false,
        "background":  false
    },
    {
        "src":  "/music-library/wanderingsoul.mp3",
        "fileName":  "WanderingSoul.mp3",
        "title":  "Wandering Soul",
        "duration":  "00:03:00",
        "description":  "An introspective track with a searching, inward character.",
        "inspiration":  "A meditation on identity, change, and the long arc of a life.",
        "featured":  false,
        "background":  false
    },
    {
        "src":  "/music-library/solotravel.mp3",
        "fileName":  "SoloTravel.mp3",
        "title":  "Solo Travel",
        "duration":  "00:03:17",
        "description":  "A personal and reflective work that suggests motion through unfamiliar places.",
        "inspiration":  "A study in independence, curiosity, and inner dialogue.",
        "featured":  false,
        "background":  false
    },
    {
        "src":  "/music-library/rockyways.mp3",
        "fileName":  "RockyWays.mp3",
        "title":  "Rocky Ways",
        "duration":  "00:02:29",
        "description":  "A piece that feels shaped by perseverance and uneven paths.",
        "inspiration":  "A musical acknowledgment of effort, resilience, and hard-earned progress.",
        "featured":  false,
        "background":  false
    },
    {
        "src":  "/music-library/lullabyforson.mp3",
        "fileName":  "LullabyForSon.mp3",
        "title":  "Lullaby for Son",
        "duration":  "00:02:29",
        "description":  "A tender, intimate composition centered on care and closeness.",
        "inspiration":  "A family piece rooted in affection, memory, and gentleness.",
        "featured":  false,
        "background":  false
    },
    {
        "src":  "/music-library/tymoteusz.mp3",
        "fileName":  "Tymoteusz.mp3",
        "title":  "Tymoteusz",
        "duration":  "00:02:29",
        "description":  "A personal dedication that gives the library a more intimate family register.",
        "inspiration":  "Presented as a named musical offering within the family story.",
        "featured":  false,
        "background":  false
    },
    {
        "src":  "/music-library/dadadance.mp3",
        "fileName":  "DadaDance.mp3",
        "title":  "Dada Dance",
        "duration":  "00:01:35",
        "description":  "A playful, rhythmic work that brings contrast and energy to the collection.",
        "inspiration":  "A lighter, more animated piece that balances the reflective tracks.",
        "featured":  false,
        "background":  false
    }
] as const satisfies readonly MusicTrack[];

export const musicSummary = {
  totalTracks: 11,
  unsupportedFiles: [],
} as const;
